import localFont from "next/font/local";

const europaGrotesk = localFont({
  src: "./fonts/EuropaGroteskSH-MedIta.otf", // adjust if different
  display: "swap",
});

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(europaGrotesk.className, "overflow-hidden")}>
        {children}
      </body>
    </html>
  );
}
